before:
  hooks:
    - make docs

builds:
  - id: pgconfigctl
    binary: pgconfigctl
    main: cmd/pgconfigctl/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64

  - id: api
    binary: api
    main: cmd/api/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X version.Tag={{.Version}} -X version.Commit={{.Commit}}
nfpms:
  - id: default
    package_name: pgconfigctl
    file_name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

    builds:
      - pgconfigctl

    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS

    homepage: https://pgconfig.org/
    maintainer: Sebastian Webber <sebastian@pgconfig.org>
    description: CLI for the pgconfig.org website

    license: MIT

    formats:
      - deb
      - rpm

archives:
  - id: pgconfigctl
    builds:
      - pgconfigctl
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
    format: binary
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc

dockers:
  - dockerfile: cmd/pgconfigctl/Dockerfile
    ids:
      - pgconfigctl
    goarch: amd64
    image_templates:
      - "pgconfig/pgconfigctl:amd64-{{ .Tag }}"

    use: buildx

    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=pgconfig-{{.ProjectName}}"
      - "--label=org.opencontainers.image.website=pgconfig.org"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - dockerfile: cmd/pgconfigctl/Dockerfile
    ids:
      - pgconfigctl
    goarch: arm64
    image_templates:
      - "pgconfig/pgconfigctl:arm64-{{ .Tag }}"

    use: buildx

    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=pgconfig-{{.ProjectName}}"
      - "--label=org.opencontainers.image.website=pgconfig.org"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

  - dockerfile: cmd/api/Dockerfile
    goarch: arm64
    ids:
      - api
    image_templates:
      - "pgconfig/api:arm64-{{ .Tag }}"
    use: buildx

    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=pgconfig-{{.ProjectName}}"
      - "--label=org.opencontainers.image.website=pgconfig.org"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"

    extra_files:
      - rules.yml
      - pg-docs.yml
  - dockerfile: cmd/api/Dockerfile
    goarch: amd64
    ids:
      - api
    image_templates:
      - "pgconfig/api:amd64-{{ .Tag }}"
    use: buildx
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=pgconfig-{{.ProjectName}}"
      - "--label=org.opencontainers.image.website=pgconfig.org"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - rules.yml
      - pg-docs.yml
docker_manifests:
  - name_template: pgconfig/api:v{{ .Tag }}
    image_templates:
      - "pgconfig/api:arm64-v{{ .Tag }}"
      - "pgconfig/api:amd64-v{{ .Tag }}"
  - name_template: "pgconfig/api:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "pgconfig/api:arm64-v{{ .Tag }}"
      - "pgconfig/api:amd64-v{{ .Tag }}"
  - name_template: "pgconfig/api:v{{ .Major }}"
    image_templates:
      - "pgconfig/api:arm64-v{{ .Tag }}"
      - "pgconfig/api:amd64-v{{ .Tag }}"
  - name_template: "pgconfig/api:latest"
    image_templates:
      - "pgconfig/api:arm64-v{{ .Tag }}"
      - "pgconfig/api:amd64-v{{ .Tag }}"
  - name_template: pgconfig/pgconfigctl:v{{ .Tag }}
    image_templates:
      - "pgconfig/pgconfigctl:arm64-v{{ .Tag }}"
      - "pgconfig/pgconfigctl:amd64-v{{ .Tag }}"
  - name_template: "pgconfig/pgconfigctl:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "pgconfig/pgconfigctl:arm64-v{{ .Tag }}"
      - "pgconfig/pgconfigctl:amd64-v{{ .Tag }}"
  - name_template: "pgconfig/pgconfigctl:v{{ .Major }}"
    image_templates:
      - "pgconfig/pgconfigctl:arm64-v{{ .Tag }}"
      - "pgconfig/pgconfigctl:amd64-v{{ .Tag }}"
  - name_template: "pgconfig/pgconfigctl:latest"
    image_templates:
      - "pgconfig/pgconfigctl:arm64-v{{ .Tag }}"
      - "pgconfig/pgconfigctl:amd64-v{{ .Tag }}"
